# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')
Task.create(title: 'Tâche 1', content: 'Description de la tâche 1')
Task.create(title: 'Tâche 2', content: 'Description de la tâche 2')
Task.create(title: 'Tâche 3', content: 'Description de la tâche 3')
Task.create(title: 'Tâche 4', content: 'Description de la tâche 4')
Task.create(title: 'Tâche 5', content: 'Description de la tâche 5')

